### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by jdent02**
Blinn BRDF

Ashikmin BRDF

### CODE REVIEW

**Comment by jdent02** [comment]
Fixes #117 and #116

**Comment by jdent02** [comment]
Also fixes #112

**Comment by jdent02** [comment]
Also fixes #75

**Comment by dictoon** [comment]
Also, Ashikmin -> Ashik**h**min, or even better Ashikhmin-Shirley.

**Comment by jdent02** [comment]
Done

**Pull request merged**
